### ISSUE TITLE
可以用你这个插件写一个地址和日期选择器吗

### ISSUE THREAD

**Issue by wangbagang** [Cople/WheelPicker#1]

**Comment by Cople** [comment]
可以参考 DEMO 里的联动来改写

**Comment by wangbagang** [comment]
还有你这个有一个问题，pc上不可以滑动也不可以点！我在火狐上测试的！

**Comment by Cople** [comment]
你应该用过火狐的「响应式设计模式」，是火狐的一个 [Bug 970346](https://bugzilla.mozilla.org/show_bug.cgi?id=1188270)

**Comment by wangbagang** [comment]
响应式设计我用了，但是我看“sui”的picker是可以，mui的picker也是可以滑动和点击的，另外我用你这个来做省市区，发现默认值设置不了的，我看了源码，在_createDom方法里面调用了setData，但是假定开始data是这样子的：[[北京,天津,上海，广东...], [北京市],[东城区，西城区...]]，value：[[浙江],[宁波],[海曙区]]，那么picker就无法初始化，初始化的结果是：浙江 北京市 东城区，后面两个错了，为什么错了，因为data里的市和区找不到宁波和海曙区。不知道你懂我的意思了把。或者那你的例子来说

`var picker3 = new WheelPicker({
    el: "#text",
    hideOnBackdrop: true,
    data: [["水果", "蔬菜"], frutiData],
    value:["蔬菜", "黄瓜"],
    onChange: function(value, index){
      console.log("onChange", value, index);
      if (index === 0) {
        this.setData(value == "水果" ? frutiData : vegetableData, 1);
      }
    },
    onSelect: function(value){
      console.log("onSelect", value);
    },
    onShow: function(){
      console.log("onShow");
    },
    onCancel: function(){
      console.log("onCancel");
    },
    parseValue: function(value) {
      return value[0] + "：" + value[1];
    }
  });`

结果：蔬菜：西瓜，不对把！

**Comment by Cople** [comment]
明白你的意思，但你填充初始数据的时候就应该填充和值对应的数据啊。
